#%RAML 1.0
title: My first touch the RAML
baseUri: http://localhost:8080/api/v1
version: 1

resourceTypes:
  collection:
    get:
      description: Fetch all <<resourcePathName|!pluralize>>
      responses:
        200:
          body:
            application/json:
              example:
                <<collection_get_example>>

    post:
      description: Create <<resourcePathName|!singularize>>
      queryParameters:
        token:
          required: true
          example:
            !include token.sample
      responses:
        200:
          body:
            application/json:
              example:
                <<collection_post_example>>

  item:
    get:
      description: Fetch specific <<resourcePathName|!singularize>>
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample
        200:
          body:
            application/json:
              example:
                <<item_get_exmaple>>
    put:
      description: Update specific <<resourcePathName|!singularize>>
      queryParameters:
        token:
          required: true
          example:
            !include token.sample
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample
        200:
          body:
            application/json:
              example:
                <<item_put_exmaple>>
    delete:
      description: Remove specific <<resourcePathName|!singularize>>
      queryParameters:
        token:
          required: true
          example:
            !include token.sample
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample
        200:
          body:
            application/json:
              example:
                <<item_delete_exmaple>>

##################### API #####################

/project:
  type:
    collection:
      collection_get_example: !include projects-colection.smaple
      collection_post_example: !include project-json.sample
  get:
    queryParameters:
        priority:
          description: Fetch all Projects with piority
          required: false
          type: integer
          example: 1
  post:
    body:
      application/json:
        example:
          !include project-create-json.sample

  /{projectId}:
    type:
      item:
        item_get_exmaple: !include project-json.sample
        item_put_exmaple: !include project-json.sample
        item_delete_exmaple: !include status-json.smaple
    put:
      body:
        application/json:
          example:
            !include project-update-request.sample