#%RAML 1.0
title: My first touch the RAML
baseUri: http://localhost:8080/api/v1
version: 1

resourceTypes:

  collection:
    get:
      description: Fetch all <<resourcePathName|!pluralize>>
      responses:
        200:
          body:
            application/json:
              example:
                !include projects-colection.smaple
    post:
      description: Create <<resourcePathName|!singularize>>
      queryParameters:
            token:
              required: true
              example:
                !include token.sample
      responses:
        200:
          body:
            application/json:
              example:
                !include project-json.sample

  item:
    get:
      description: Fetch specific <<resourcePathName|!singularize>>
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample
    put:
      description: Update specific <<resourcePathName|!singularize>>
      queryParameters:
              token:
                required: true
                example:
                  !include token.sample
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample
    delete:
      description: Remove specific <<resourcePathName|!singularize>>
      queryParameters:
              token:
                required: true
                example:
                  !include token.sample
      responses:
        404:
          body:
            application/json:
              !include not-found-error-json.sample

##################### API #####################

/project:
  type: collection

  get:
    queryParameters:
        priority:
          description: Fetch all Projects with piority
          required: false
          type: integer
          example: 1

  post:
    body:
      application/json:
        example:
          !include project-create-json.sample


  /{projectId}:
    type: item

    get:
      responses:
        200:
          body:
            application/json:
              example:
                !include project-json.sample

    put:
      body:
        application/json:
          example:
            !include project-update-request.sample
      responses:
        200:
          body:
            application/json:
              example:
                !include project-json.sample

    delete:
      responses:
        200:
          body:
            application/json:
              example:
                !include status-json.smaple
